portal_forum/user_activity/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, widgets, SelectMultipleField, HiddenField
from wtforms.validators import DataRequired, ValidationError, NumberRange
from wtforms.fields import html5 as h5fields
from wtforms.widgets import html5 as h5widgets
from portal_forum.models import Album

class ThreadForm(FlaskForm):
    topic = StringField('Temat wątku', validators=[DataRequired()])
    description = TextAreaField('Opis')

class PostForm(FlaskForm):
    reply = TextAreaField('Odpowiedź')

class CommentForm(FlaskForm):
    reply = StringField('Odpowiedź', validators=[DataRequired()])

class TrackForm(FlaskForm):
    title = StringField('Tytuł', validators=[DataRequired()])
    date_release = h5fields.IntegerField("Rok wydania", widget=h5widgets.NumberInput(), validators=[NumberRange(min=1970, max=2021, message="Wporwadź poprawny rok")])
    lyrics = TextAreaField('Tekst', validators=[DataRequired()])
    description = TextAreaField('Opis utworu')
    lyrics_by = StringField('Autor tekstu')
    '''(Proteza)
    <div class="form-group">
                        <label class="form-control-label">
                            Albumy
                        </label>
                    <table>
                        {% for album in albums %}
                            <tr>
                                <td><input type="checkbox" name="albums" value="{{ album.id }}"></td>
                                <td> {{ album.title }} ({{ album.date_release }})</td>
                            </tr>

                        {% endfor %}
                    </table>
                    </div>
    '''
def validate_scrap(form, scrap_description):

    if len(scrap_description.data) < 2:
        raise ValidationError('Oznaczono za krótki fragment.')

class ScrapForm(FlaskForm):
    description = TextAreaField('Fragment', validators=[DataRequired()])
    lyrics_with_scraps = HiddenField("zaznaczone fragmenty")
    '''index_from = HiddenField("scrap-text-start", validators=[DataRequired()])
    index_to = HiddenField("scrap-text-end", validators=[DataRequired()])'''

class InterpretationForm(FlaskForm):
    title = StringField('Temat', validators=[DataRequired()])
    text = TextAreaField('tekst', validators=[DataRequired()])

class TranslationForm(FlaskForm):
    title = StringField('Temat', validators=[DataRequired()])
    text = TextAreaField('tekst')

class OpinionForm(FlaskForm):
    reply = TextAreaField('Opinia', validators=[DataRequired()])

portal_forum/user_activity/routes.py
import sys
from functools import wraps

from flask import render_template, url_for, redirect, flash, request, abort, Blueprint, g, json
from markupsafe import Markup
from sqlalchemy import desc, asc
from portal_forum.user_activity.forms import ThreadForm, PostForm, TrackForm, ScrapForm, InterpretationForm, \
    OpinionForm, TranslationForm, CommentForm
from portal_forum import db
from portal_forum.models import Thread, User, Thread_Post, Track, Album, Scrap, Track_Post, Interpretation, \
    Interpretation_Opinion, Translation_Opinion, Translation, Scrap_Rating, Translation_Rating, Interpretation_Rating, \
    Scrap_Opinion, Scrap_last_id
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime
from portal_forum.users.utils import check_image
from portal_forum.user_activity.utils import clear_track, clear_target, to_admin_delete, login_my_required
import re

user_activity = Blueprint('user_activity', __name__)


@user_activity.route('/threads', methods=['GET', 'POST'])
def threads():
    strona = request.args.get('strona', 1, type=int)
    threads = Thread.query.order_by(desc(Thread.date_last_update)).paginate(page=strona, per_page=5)
    return render_template('threads.html', title="Wątki | Tom Waits", image_file=check_image(), threads=threads)


@user_activity.route('/thread/<int:thread_id>', methods=['GET', 'POST'])
def thread(thread_id):
    thread = Thread.query.get_or_404(thread_id)
    tags = Markup(thread.description)
    posts = Thread_Post.query. \
        filter_by(thread=thread). \
        order_by(asc(Thread_Post.date_posted))
    replies = []
    for post in posts:
        replies.append(Markup(post.reply))
    return render_template('thread.html', title=thread.topic+" | Tom Waits", image_file=check_image(), thread=thread, tags=tags,
                           posts=posts, replies=replies)


@user_activity.route('/thread/new', methods=['GET', 'POST'])
@login_my_required
def new_thread():
    form = ThreadForm()
    if form.validate_on_submit():
        thread = Thread(topic=form.topic.data, description=form.description.data, author=current_user)
        db.session.add(thread)
        db.session.commit()
        flash("Wątek został dodany", "success")
        return redirect(url_for('main.forum'))
    return render_template('create_thread.html', title="Nowy wątek | Tom Waits",
                           legend="Rozpocznij nowy wątek", form=form, image_file=check_image())


@user_activity.route('/thread/<int:thread_id>/update', methods=['GET', 'POST'])
@login_my_required
def update_thread(thread_id):
    thread = Thread.query.get_or_404(thread_id)
    if thread.author != current_user:
        abort(403)
    form = ThreadForm()
    if form.validate_on_submit():
        thread.topic = form.topic.data
        thread.description = form.description.data
        thread.date_last_update = datetime.strptime(str(datetime.utcnow()), "%Y-%m-%d %H:%M:%S.%f")
        db.session.commit()
        flash("Wątek zaktualizowany!", 'success')
        return redirect(url_for('user_activity.thread', thread_id=thread.id))
    elif request.method == "GET":
        form.topic.data = thread.topic
        form.description.data = thread.description
    return render_template('create_thread.html', title="Edytuj wątek | Tom Waits",
                           legend="Edytuj wątek", form=form, image_file=check_image(), thread_id=thread_id)


@user_activity.route('/thread/<int:thread_id>/delete', methods=['POST'])
@login_my_required
def delete_thread(thread_id):
    thread = Thread.query.get_or_404(thread_id)
    if thread.author != current_user and not current_user.is_admin:
        abort(403)
    if not current_user.is_admin and len(thread.threads) > 0:
        to_admin_delete('thread', thread_id)
        return redirect(url_for('user_activity.thread', thread_id=thread.id))
    elif current_user.is_admin and len(thread.threads) > 0:
        for post in thread.threads:
            db.session.delete(post)
        db.session.delete(thread)
        db.session.commit()
    elif len(thread.threads) == 0:
        db.session.delete(thread)
        db.session.commit()
    flash("Wątek usunięty", 'success')
    return redirect(url_for('user_activity.threads'))


@user_activity.route('/thread/<int:thread_id>/reply', methods=['GET', 'POST'])
@login_my_required
def thread_reply(thread_id):
    form = PostForm()
    if form.validate_on_submit():
        post = Thread_Post(reply=form.reply.data, author=current_user, thread_id=thread_id)
        db.session.add(post)
        db.session.commit()
        flash("Odpowiedź została dodana", "success")
        return redirect(url_for('user_activity.thread', thread_id=thread_id))
    return render_template('thread_reply.html', title="Rozwiń wątek | Tom Waits",
                           legend="Odpowiedz", form=form, image_file=check_image(),
                           thread_id=thread_id, reply_id=None)


@user_activity.route('/thread/<int:thread_id>/reply_to/<int:post_id>', methods=['GET', 'POST'])
@login_my_required
def quote_thread_post(thread_id, post_id):
    post = Thread_Post.query.get_or_404(post_id)
    form = PostForm()
    date_posted = post.date_posted
    date_posted = date_posted.strftime('%Y-%m-%d %H:%M')
    quote = "<div>" \
            "<div style='background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;'>" \
            "<b>" + post.author.username + "</b> powiedział " + date_posted + \
            "</div>" \
            "<blockquote class='cke_contents_ltr blockquote'>" + post.reply + "</blockquote>" \
                                                                              "<p></p></div>"
    if form.validate_on_submit():
        post = Thread_Post(reply=form.reply.data, author=current_user, thread_id=thread_id)
        db.session.add(post)
        db.session.commit()
        flash("Odpowiedź została dodana", "success")
        return redirect(url_for('user_activity.thread', thread_id=thread_id))
    elif request.method == "GET":
        form.reply.data = Markup(quote)
    return render_template('thread_reply.html', title="Rozwiń wątek | Tom Waits",
                           legend="Odpowiedz użytkownikowi " + post.author.username, form=form,
                           image_file=check_image(),
                           thread_id=thread_id, reply_id=None)


@user_activity.route('/thread/<int:thread_id>/reply/<int:post_id>/update', methods=['GET', 'POST'])
@login_my_required
def update_thread_post(post_id, thread_id):
    post = Thread_Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.reply = form.reply.data
        post.date_last_update = datetime.strptime(str(datetime.utcnow()), "%Y-%m-%d %H:%M:%S.%f")
        db.session.commit()
        flash("Odpowiedź została zaktualizowana!", 'success')
        return redirect(url_for('user_activity.thread', thread_id=thread_id))
    elif request.method == "GET":
        form.reply.data = post.reply
    return render_template('thread_reply.html', title="Edytuj odpowiedź | Tom Waits",
                           legend="Edytuj odpowiedź", form=form,
                           image_file=check_image(), thread_id=thread_id)


@user_activity.route('/thread/<int:thread_id>/reply/<int:post_id>/delete', methods=['POST'])
@login_my_required
def delete_thread_post(thread_id, post_id):
    post = Thread_Post.query.get_or_404(post_id)
    if post.author != current_user and not current_user.is_admin:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Odpowiedź została usunięta", 'success')
    return redirect(url_for('user_activity.thread', thread_id=thread_id))


@login_my_required
@user_activity.route('/track/<int:track_id>', methods=['GET', 'POST'])
def track(track_id):
    track = Track.query.get_or_404(track_id)
    tags = Markup(track.lyrics)
    comments = Track_Post.query. \
        filter_by(track=track). \
        order_by(asc(Track_Post.date_posted))
    tags_description = Markup(track.description)

    replies = []
    for comment in comments:
        replies.append(Markup(comment.reply))

    return render_template('track.html', title=track.title+" | Tom Waits", image_file=check_image(), track=track, tags=tags,
                           tags_description=tags_description, comments=comments, replies=replies)


@user_activity.route('/tracks', methods=['GET', 'POST'])
@login_my_required
def tracks():
    strona = request.args.get('strona', 1, type=int)
    tracks = Track.query.order_by(desc(Track.date_last_update)).paginate(page=strona, per_page=5)
    return render_template('tracks.html', title="Utwory | Tom Waits", image_file=check_image(), tracks=tracks)


@user_activity.route('/tracks/new', methods=['GET', 'POST'])
@login_my_required
def new_track():
    form = TrackForm()
    albums = Album.query.all()

    if form.validate_on_submit():
        albums_list = request.form.getlist("albums")
        tags = form.lyrics.data
        tags = tags.replace("<p>", '')
        tags = tags.replace("</p>", "<br/>")
        tags = tags.replace("&oacute;", "ó")
        tags = tags.replace("&Oacute;", "Ó")
        track = Track(title=form.title.data, lyrics=tags, lyrics_with_scraps=tags, author=current_user,
                      date_release=form.date_release.data, lyrics_by=form.lyrics_by.data,
                      description=form.description.data)

        for cd in albums_list:
            album = Album.query.filter_by(id=int(cd)).first_or_404()

            track.albums.append(album)
        db.session.add(track)
        db.session.commit()

        db.session.commit()
        flash("Utwór został dodany", "success")
        return redirect(url_for('user_activity.tracks'))

    return render_template('create_track.html', title="Nowy Utwór | Tom Waits", albums=albums,

portal_forum/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request, g

from portal_forum.user_activity.utils import login_my_required
from portal_forum.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from portal_forum import db, bcrypt
from portal_forum.models import User
from flask_login import login_user, current_user, logout_user
from portal_forum.users.utils import save_image

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if User.query.filter_by(is_admin=True).first() is None:
        hashed_password = bcrypt.generate_password_hash("admin123").decode('utf-8')
        admin = User(username="Admin", email="true.admin@mail.com", password=hashed_password, is_admin=True)
        db.session.add(admin)
        db.session.commit()
    if current_user.is_authenticated:
        return redirect(url_for('main.forum'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, is_admin=False)
        db.session.add(user)
        db.session.commit()
        flash('Twoje konto utworzono pomyślnie!', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title="Rejestracja", form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.forum'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.forum'))
        else:
            flash('Wprowadzono niepoprawne dane', 'danger')
    return render_template('login.html', title="Logowanie", form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.forum'))


@users.route('/account', methods=['GET', 'POST'])
@login_my_required
def account():
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            image_file = save_image(form.picture.data)
            current_user.image_file = image_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Twoje dane zostały zaktualizowane', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title="Konto użytkownika", image_file=image_file, form=form)

portal_forum/templates/forum-home.html
{% extends "forum-layout.html" %}
{% block content %}
    <div id="colage">
        <img class="forum_img instruction_img"
             src="{{ url_for('static', filename="images/3619810051_02c3dbe30d_e.jpg") }}">
        <img class="forum_img instruction_img"
             src="{{ url_for('static', filename="images/3619810751_5a91292856_e.jpg") }}">
        <br class="full-none">
        <img class="forum_img instruction_img"
             src="{{ url_for('static', filename="images/3620628636_4519558c9d_e.jpg") }}">
        <img class="forum_img instruction_img"
             src="{{ url_for('static', filename="images/3620628766_a92f1584b4_e.jpg") }}">
    </div>
    <div class="card">
        <div class="card-header">
            Ostatnia aktywność
        </div>
        <div class="card-body">
            <table class="table hide-mobile">
                <thead class="thead-primary">
                <tr>
                    <th scope="col">Dodano</th>
                    <th scope="col">Przez</th>
                    <th scope="col">Temat</th>
                    <th scope="col" class="hide-mobile">Odpowiedzi</th>
                    <th scope="col" class="hide-mobile">Ostatnia aktualizacja</th>
                </tr>
                </thead>
                <tbody>
                {% for thread in threads %}
                    <tr>
                        <td>{{ thread.date_posted.strftime('%Y-%m-%d %H:%M') }}</td>
                        <td>
                            <a class="mr-2 grey-link"
                               href="{{ url_for("user_activity.user_actions", username=thread.author.username) }}">{{ thread.author.username }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ url_for('user_activity.thread', thread_id=thread.id) }}" class="grey-link">
                                {{ thread.topic }}
                            </a>
                        </td>
                        <td>{{ thread.threads|length }}</td>
                        {% if thread.threads|length > 0 and thread.threads[thread.threads|length-1].date_posted > thread.date_last_update %}
                            <td>{{ thread.threads[thread.threads|length-1].date_posted.strftime('%Y-%m-%d %H:%M') }}</td>
                        {% else %}
                            <td>{{ thread.date_last_update.strftime('%Y-%m-%d %H:%M') }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="elements-table">
                {% for thread in threads %}
                    <div class="table-row">
                        <div class="table-cell">
                            Dodano:
                            <div style="display: inline-block">{{ thread.date_posted.strftime('%Y-%m-%d %H:%M') }}</div>
                            <br>
                            Przez: <a class="mr-2 grey-link"
                                      href="{{ url_for("user_activity.user_actions", username=thread.author.username) }}">{{ thread.author.username }}
                        </a>
                        </div>
                        <div class="table-cell">
                            Temat:
                            <a href="{{ url_for('user_activity.thread', thread_id=thread.id) }}"
                               class="grey-link">
                                {{ thread.topic }}
                            </a><br>
                            Odpowiedzi: {{ thread.threads|length }}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <a href="{{ url_for("user_activity.threads") }}"
               class="btn bg-dark text-white responsive-full responsive-marg-6">Zobacz wszystkie wątki</a>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for("user_activity.new_thread") }}" class="btn bg-dark text-white responsive-full">
                    <svg xmlns="url_for('static', filename='/images/plus-circle.svg/')" width="20" height="20"
                         fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                    Rozpocznij nowy wątek
                </a>
            {% endif %}
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            Ostatnio dodane utwory
        </div>
        {% if current_user.is_authenticated %}
            <div class="card-body">
                <table class="table hide-mobile">
                    <thead class="thead-primary">
                    <tr>
                        <th scope="col">Dodano</th>
                        <th scope="col" class="hide-mobile">Przez</th>
                        <th scope="col">Albumy</th>

                        <th scope="col">Tytuł</th>
                        <th scope="col" class="hide-mobile">Ostatnia aktualizacja</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for track in tracks %}
                        <tr>
                            <td>{{ track.date_posted.strftime('%Y-%m-%d %H:%M') }}</td>
                            <td class="hide-mobile">
                                <a class="grey-link"
                                   href="{{ url_for("user_activity.user_actions", username=track.author.username) }}">
                                    {{ track.author.username }}
                                </a>
                            </td>

                            <td>
                                {% for album in track.albums %}
                                    {% if loop.index < track.albums|length %}
                                        {{ album.title }},
                                    {% else %}
                                        {{ album.title }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{{ url_for('user_activity.track', track_id=track.id) }}" class="grey-link">
                                    {{ track.title }}
                                </a>
                            </td>
                            {% if track.comments|length > 0 and track.comments[track.comments|length-1].date_posted > track.date_last_update %}
                                <td class="hide-mobile">{{ track.comments[track.comments|length-1].date_posted.strftime('%Y-%m-%d %H:%M') }}</td>
                            {% else %}
                                <td class="hide-mobile">{{ track.date_last_update.strftime('%Y-%m-%d %H:%M') }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="elements-table">
                    {% for track in tracks %}
                        <div class="table-row">
                            <div class="table-cell">
                                Dodano:
                                <div style="display: inline-block">{{ track.date_posted.strftime('%Y-%m-%d %H:%M') }}</div>
                                <br>
                                Przez: <a class="mr-2 grey-link"
                                          href="{{ url_for("user_activity.user_actions", username=track.author.username) }}">{{ track.author.username }}
                            </a>
                            </div>
                            <div class="table-cell">
                                Tytuł:
                                <a href="{{ url_for('user_activity.track', track_id=track.id) }}"
                                   class="grey-link">
                                    {{ track.title }}
                                </a><br>
                                Albumy:
                                {% for album in track.albums %}
                                    {% if loop.index < track.albums|length %}
                                        {{ album.title }},
                                    {% else %}
                                        {{ album.title }}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a href="{{ url_for("user_activity.tracks") }}"
                   class="btn bg-dark text-white responsive-full responsive-marg-6">Zobacz wszystkie utwory</a>
                <a href="{{ url_for("user_activity.new_track") }}" class="btn bg-dark text-white responsive-full">
                    <svg xmlns="url_for('static', filename='/images/plus-circle.svg/')" width="20" height="20"
                         fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                    Dodaj nowy utwór
                </a>
            </div>
        {% else %}
            <div class="card-body">
                <h5 class="card-title">Dyskusje o utworach</h5>
                <p class="card-text"><a href="{{ url_for("users.login") }}" class="grey-link">Zaloguj się</a> lub <a
                        class="grey-link" href="{{ url_for("users.register") }}">zarejestruj</a>, żeby brać udział w
                    dyskusjach.</p>
            </div>
        {% endif %}
    </div>
    <div class="image-view">
        <img id="big-image" src="" alt="image_bigger_view">
        <div class="image-view-description">
            <h3>Autor - Anton Corbijn</h3>
            <h4>Źródło - <a class="grey-link" href="http://www.tomwaits.com/">tomwaits.com</a></h4>
        </div>
    </div>
    <script>
        $(".instruction_img").click(function () {
            var src = $(this).attr("src");
            $(".image-view").show();
            $("#big-image").attr("src", src);
        });
        $(".image-view").click(function () {
            $(".image-view").hide();
        });
    </script>
{% endblock content %}

portal_forum/templates/threads.html
{% extends "forum-layout.html" %}
{% block content %}
    <div class="card">
        <div class="card-header">
            Wątki
        </div>
        <div class="card-body">
            {% for page_num in threads.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if threads.page == page_num %}
                        <a class="btn btn-dark"
                           href="{{ url_for("user_activity.threads", strona=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-dark"
                           href="{{ url_for("user_activity.threads", strona=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}

            {% endfor %}
            <table class="table hide-mobile" style="margin-bottom: 5px; margin-top: 5px">
                <thead class="thead-primary">
                <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Autor</th>
                    <th scope="col">Temat</th>
                    <th scope="col" class="hide-mobile">Odpowiedzi</th>
                    <th scope="col" class="hide-mobile">Ostatnia aktualizacja</th>
                </tr>
                </thead>
                <tbody>
                {% for thread in threads.items %}
                    <tr>
                        <td>{{ thread.date_posted.strftime('%Y-%m-%d %H:%M') }}</td>
                        <td>
                            <a class="mr-2 grey-link"
                               href="{{ url_for("user_activity.user_actions", username=thread.author.username) }}">{{ thread.author.username }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ url_for('user_activity.thread', thread_id=thread.id) }}" class="grey-link">
                                {{ thread.topic }}
                            </a>
                        </td>
                        <td class="hide-mobile">{{ thread.threads|length }}</td>
                        <td class="hide-mobile">{{ thread.date_last_update.strftime('%Y-%m-%d %H:%M') }}</td>

                    </tr>
                {% endfor %}


                </tbody>
            </table>
            <div class="elements-table" style="margin-bottom: 5px; margin-top: 5px">
                {% for thread in threads.items %}
                    <div class="table-row">
                        <div class="table-cell">
                            Dodano: <div style="display: inline-block"> {{ thread.date_posted.strftime('%Y-%m-%d %H:%M') }}</div><br>
                            Przez: <a class="mr-2 grey-link"
                                      href="{{ url_for("user_activity.user_actions", username=thread.author.username) }}">{{ thread.author.username }}
                        </a>
                        </div>
                        <div class="table-cell">
                            Temat:
                            <a href="{{ url_for('user_activity.thread', thread_id=thread.id) }}"
                               class="grey-link">
                                {{ thread.topic }}
                            </a><br>
                            Odpowiedzi: {{ thread.threads|length }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% for page_num in threads.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if threads.page == page_num %}
                        <a class="btn btn-dark"
                           href="{{ url_for("user_activity.threads", strona=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-dark"
                           href="{{ url_for("user_activity.threads", strona=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <a href="{{ url_for("user_activity.new_thread") }}" class="btn bg-dark text-white responsive-full mb-2">
        <svg xmlns="url_for('static', filename='/images/plus-circle.svg/')" width="20" height="20"
             fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
        Rozpocznij nowy wątek
    </a>
    <a href="{{ url_for("main.forum") }}"
       class="btn bg-dark text-white responsive-full mb-2">Powrót</a>
{% endblock content %}